### ISSUE TITLE
System.IO.FileNotFoundException : Could not load file or assembly 'Faker.Net.Standard.2.0, Version=1.5.136.0

### ISSUE THREAD

**Issue by ManikandanMani** [oriches/faker-cs#16]
![image](https://user-images.githubusercontent.com/42301172/118149865-98813800-b42f-11eb-9523-736cfee205bf.png)
Unable to use  faker references from  .net standard 2.0 which is referenced to a .net framework V4.8 test project , the compile time assembly of faker included in a .net standard project  is changed to .net framework.

**Comment by Siliconrob** [comment]
Yes, this sucks.   Would you like to submit a fix?

**Comment by Siliconrob** [comment]
@ManikandanMani I can't replicate it can you upload your project somewhere please?

**Comment by ManikandanMani** [comment]
> @ManikandanMani I can't replicate it can you upload your project somewhere please?

@Siliconrob  https://github.com/ManikandanMani/FakerIssueRepro

**Comment by ManikandanMani** [comment]
@Siliconrob , @oriches I assume  based on this  (https://github.com/dotnet/runtime/issues/25770) the issue is caused seems theyhave mentioned that it were fixed it in net472 (https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/514195-Targeting%20.NET%20Framework%204.7.1%20copies%20extra%20files%20to%20your%20bin%20directory.md) but i tried targetting net 472 & 48 but didn't  resolve , one work around is adding the faker dll under reference include didn't throw any exception instead of adding under package reference include .
![image](https://user-images.githubusercontent.com/42301172/118385679-c7b1c800-b62e-11eb-96b9-2c660412309e.png)

**Comment by Siliconrob** [comment]
Give me a day or so to look over it.  Thanks for the upload

**Comment by Siliconrob** [comment]
@ManikandanMani  I was able to reproduce your issue and I tracked it down to the embedded resource.  I made some slight changes to the project linking for the resources and it was fine.  Here is the fix I think will get this working #17 

@oriches can you review?

**Comment by Siliconrob** [comment]
@oriches Would you publish the change in #17 to nuget please

**Comment by oriches** [comment]
Pushed, but i think we still have the issue after testing.

Let me know what you see...

------ Original Message ------
From: "Siliconrob" ***@***.***>
To: "oriches/faker-cs" ***@***.***>
Cc: "Ollie Riches" ***@***.***>; "Mention" 
***@***.***>
Sent: Tuesday, 18 May, 21 At 18:50
Subject: Re: [oriches/faker-cs] System.IO.FileNotFoundException : Could 
not load file or assembly 'Faker.Net.Standard.2.0, Version=1.5.136.0 
(#16)


@oriches <https://github.com/oriches>  Would you publish the change in 
#17 <https://github.com/oriches/faker-cs/pull/17>  to nuget please
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/oriches/faker-cs/issues/16#issuecomment-843400691> , 
or unsubscribe

**Comment by Siliconrob** [comment]
😦😖😞 I will check it tonight, but if it doesn't work I will do further investigation.

**Comment by oriches** [comment]
I think the nuGet spec is wrong for 4.6 - 4.8 versions, I think they need to be the .net standard versions 2.0 - 2.1, so when they are referenced they will be the correct assemblies when referencing a .net standard project in a .net 4.8 project where Faker is unused from nuGet.On 18 May 2021 19:19, Siliconrob ***@***.***> wrote:

😦😖😞 I will check it tonight, but if it doesn't work I will do further investigation.

**Comment by Siliconrob** [comment]
Yes, you are right it doesn't work.  I have an idea about multi-targeting the framework for the library, but it's not working so far.  Does this even sound like a good idea?

**Comment by Siliconrob** [comment]
Multi target did not solve issue.  Open to suggestions, but not sure why you want to use NUnit 4.8 framework for tests.  Switch to .NET Core or use Xunit is what I would say to do @ManikandanMani

**Comment by oriches** [comment]
I have an idea of around hacking the nuGet package once installed for 
the project, if it works it measn changing the nuSpec only, I'll try and 
find sometime later this week.

Thanks
Ollie

------ Original Message ------
From: "Siliconrob" ***@***.***>
To: "oriches/faker-cs" ***@***.***>
Cc: "Ollie Riches" ***@***.***>; "Mention" 
***@***.***>
Sent: Sunday, 23 May, 21 At 22:04
Subject: Re: [oriches/faker-cs] System.IO.FileNotFoundException : Could 
not load file or assembly 'Faker.Net.Standard.2.0, Version=1.5.136.0 
(#16)


Multi target did not solve issue.  Open to suggestions, but not sure why 
you want to use NUnit 4.8 framework for tests.  Switch to .NET Core or 
use Xunit is what I would say to do @ManikandanMani 
<https://github.com/ManikandanMani>
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/oriches/faker-cs/issues/16#issuecomment-846624257> , 
or unsubscribe

**Comment by ManikandanMani** [comment]
> Multi target did not solve issue. Open to suggestions, but not sure why you want to use NUnit 4.8 framework for tests. Switch to .NET Core or use Xunit is what I would say to do @ManikandanMani

@Siliconrob  Since our project need xrm.sdk dll which supports only net frameworks , when referencing it other projects types doesn't support xrm.sdk dlls. so net framework was the only option.

**Comment by Siliconrob** [comment]
> > Multi target did not solve issue. Open to suggestions, but not sure why you want to use NUnit 4.8 framework for tests. Switch to .NET Core or use Xunit is what I would say to do @ManikandanMani
> 
> @Siliconrob Since our project need xrm.sdk dll which supports only net frameworks , when referencing it other projects types doesn't support xrm.sdk dlls. so net framework was the only option.

🙁😿

Waiting for what @oriches can turn up
